[package]
name = "wacore-binary"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
serde = ["dep:serde"]

[dependencies]
flate2 = { version = "1.0", default-features = false, features = ["zlib-rs"] }
phf = { version = "0.12.1", features = ["macros"] }
serde = { version = "1.0", features = ["derive"], optional = true }

[build-dependencies]
phf_codegen = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
